In [86]:
import numpy as np
def mp_neuron(inputs, threshold):
    return 1 if sum(inputs) > threshold else 0
np.random.seed(42)
n_samples = 500
age = np.random.randint(20, 60, n_samples)
salary = np.random.randint(20000, 150000, n_samples)
family = np.random.randint(1, 7, n_samples)
X = np.column_stack((age, salary, family))
true_threshold = 100000
y = np.array([1 if sum(x) > true_threshold else 0 for x in X])
print("First 5 records of X:\n", X[:5])

First 5 records of X:
 [[   58 71934     1]
 [   48 84895     1]
 [   34 52307     5]
 [   27 74098     6]
 [   40 80921     5]]


In [88]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import time
start_time=time.time()
def min_max_scale(X):
    X = np.array(X, dtype=np.float64)
    return (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = min_max_scale(X)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)
class SigmoidNeuron:
    def __init__(self, n_inputs, lr=0.1):
        self.weights = np.random.randn(n_inputs)
        self.bias = np.random.randn()
        self.lr = lr
    def sigmoid(self, z):
        z = np.clip(z, -500, 500)
        return 1 / (1 + np.exp(-z))
    def forward(self, X):
        z = np.dot(X, self.weights) + self.bias
        return self.sigmoid(z)
    def train(self, X, y, epochs=1000):
        for _ in range(epochs):
            output = self.forward(X)
            error = output - y
            self.weights -= self.lr * np.dot(X.T, error) / len(X)
            self.bias -= self.lr * np.mean(error)
model = SigmoidNeuron(n_inputs=3, lr=0.5)
model.train(X_train, y_train, epochs=2000)
probs = model.forward(X_test)
predictions = (probs >= 0.5).astype(int)
accuracy = accuracy_score(y_test, predictions)
print("\nFirst 5 Probabilities:")
for i, p in enumerate(probs[:5], 1):
    print(f"Sample {i}: {p:.4f}")
print("Accuracy:", accuracy)
start = time.time()
model.train(X_train, y_train, epochs=2000)
end = time.time()
print("\n--- RAW DATA ---")
print("Training Time:", raw_time)
print("Accuracy:", raw_acc)
print("\n--- NORMALIZED DATA ---")
print("Training Time:", scaled_time)
print("Accuracy:", scaled_acc)


First 5 Probabilities:
Sample 1: 0.9920
Sample 2: 0.0103
Sample 3: 0.0024
Sample 4: 0.0009
Sample 5: 0.4907
Accuracy: 0.97

--- RAW DATA ---
Training Time: 0.06674313545227051
Accuracy: 0.38

--- NORMALIZED DATA ---
Training Time: 0.07220292091369629
Accuracy: 0.98


In [84]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y = np.array([0, 1, 1, 0])
model = SigmoidNeuron(n_inputs=2, lr=0.5)
model.train(X, y, epochs=5000)
probs = model.forward(X)
preds = (probs >= 0.5).astype(int)

print("XOR Predictions:", preds)

XOR Predictions: [1 1 1 1]
